# Generated by Django 3.0.8 on 2020-07-07 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0002_auto_20200706_0335'),
        ('company', '0002_auto_20200706_0318'),
        ('centraldata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('nim', models.CharField(default='', max_length=255)),
                ('intern_year', models.IntegerField(default='', max_length=20)),
                ('start_date', models.DateField(default='')),
                ('end_date', models.DateField(default='')),
                ('proposal', models.FileField(blank=True, upload_to='')),
                ('report', models.FileField(blank=True, upload_to='')),
                ('handout', models.FileField(blank=True, upload_to='')),
                ('ppt_seminar', models.FileField(blank=True, upload_to='')),
                ('publication_link', models.CharField(default='', max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('intern_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
                ('lecturer_adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centraldata.Student')),
            ],
        ),
    ]
