# Generated by Django 3.0.8 on 2020-07-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='intern_year',
            field=models.IntegerField(default=''),
        ),
    ]
