# Generated by Django 3.0.8 on 2020-07-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='poster',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
