# Generated by Django 3.0.8 on 2020-08-12 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centraldata', '0013_remove_student_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internships', '0002_internship_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='ppt_seminar',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='seminar_date',
        ),
        migrations.AddField(
            model_name='internship',
            name='member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='centraldata.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='ppt',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='internship',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='internship',
            name='group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='internship',
            name='handout',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internship',
            name='proposal',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='report',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
