# Generated by Django 3.0.8 on 2020-07-08 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
        ('centraldata', '0001_initial'),
        ('internships', '0002_auto_20200707_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='nim',
        ),
        migrations.AlterField(
            model_name='internship',
            name='lecturer_adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.Lecturer'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centraldata.Student'),
        ),
    ]
