# Generated by Django 3.0.8 on 2020-07-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('nim', models.CharField(default='', max_length=255)),
                ('generation', models.IntegerField(default='')),
                ('email', models.CharField(default='', max_length=255)),
                ('avatar', models.ImageField(blank=True, default='', upload_to='')),
                ('address', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('province', models.CharField(default='', max_length=255)),
                ('postal_code', models.IntegerField(default='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
