# Generated by Django 3.0.8 on 2020-07-10 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centraldata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='student_address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='city',
            new_name='student_city',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='student_email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='generation',
            new_name='student_generation',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='nim',
            new_name='student_nim',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='postal_code',
            new_name='student_postal_code',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='province',
            new_name='student_province',
        ),
    ]
