# Generated by Django 3.0.8 on 2020-07-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centraldata', '0002_auto_20200710_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
