# Generated by Django 3.0.8 on 2020-07-11 10:19

import awesome_avatar.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centraldata', '0004_auto_20200711_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_avatar',
            field=awesome_avatar.fields.AvatarField(upload_to='student_avatar'),
        ),
    ]
