# Generated by Django 3.0.8 on 2020-07-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centraldata', '0006_auto_20200711_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_avatar',
            field=models.ImageField(blank=True, default='', upload_to='pics'),
        ),
    ]
