# Generated by Django 3.0.8 on 2020-07-14 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centraldata', '0008_auto_20200713_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_avatar',
            new_name='file',
        ),
    ]
