# Generated by Django 3.0.8 on 2020-07-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centraldata', '0010_auto_20200714_0410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_generation',
            new_name='student_number_phone',
        ),
    ]
