# Generated by Django 3.0.8 on 2020-08-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centraldata', '0011_auto_20200714_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_address',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_city',
            new_name='nim',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_number_phone',
            new_name='number_phone',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_postal_code',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_nim',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_province',
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='province',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='rt_village',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='rw_village',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='sub_district',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='village',
            field=models.CharField(default='', max_length=50),
        ),
    ]
