# Generated by Django 3.0.8 on 2020-08-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centraldata', '0012_auto_20200804_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
    ]
