# Generated by Django 3.0.8 on 2020-08-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centraldata', '0013_remove_student_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
