# Generated by Django 3.0.8 on 2020-07-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200720_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nim',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='number_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
