# Generated by Django 3.0.8 on 2020-08-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200720_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='uploads'),
        ),
    ]
