# Generated by Django 3.0.8 on 2020-07-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('business', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('website', models.EmailField(blank=True, default='', max_length=255)),
                ('pic_name', models.CharField(blank=True, default='', max_length=255)),
                ('pic_number', models.CharField(blank=True, default='', max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
