# Generated by Django 3.0.8 on 2020-07-08 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centraldata', '0001_initial'),
        ('company', '0002_auto_20200706_0318'),
        ('lecturers', '0001_initial'),
        ('topics', '0002_auto_20200706_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesis_title', models.CharField(default='', max_length=255)),
                ('graduate_year', models.IntegerField(default='')),
                ('thesis_proposal', models.FileField(blank=True, upload_to='')),
                ('thesis_report', models.FileField(blank=True, upload_to='')),
                ('thesis_handout', models.FileField(blank=True, upload_to='')),
                ('thesis_ppt', models.FileField(blank=True, upload_to='')),
                ('publication_link', models.CharField(default='', max_length=255)),
                ('start_date', models.DateField(blank=True, default='')),
                ('end_date', models.DateField(blank=True, default='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('company_name', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('lecturer_adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.Lecturer')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centraldata.Student')),
                ('thesis_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
            ],
        ),
    ]
