# Generated by Django 3.0.8 on 2020-08-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_auto_20200811_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='thesis_handout',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='thesis_ppt',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='thesis_proposal',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='thesis_report',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
