# Generated by Django 3.0.8 on 2020-08-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_auto_20200811_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='thesis_proposal',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
