# Generated by Django 3.0.8 on 2020-08-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_auto_20200811_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='thesis_proposal',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
