# Generated by Django 3.0.8 on 2020-08-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0006_auto_20200811_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='nim',
        ),
    ]
