# Generated by Django 3.0.8 on 2020-08-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0007_remove_thesis_nim'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='internship_status',
            field=models.BooleanField(default=False),
        ),
    ]
