# Generated by Django 3.0.8 on 2020-08-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0008_thesis_internship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='end_date',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='start_date',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
    ]
