# Generated by Django 3.0.8 on 2020-08-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
